minVersion: 2.21.6
changelogPolicy: auto
preReleaseCommand: "scripts/bump-version.sh"
postReleaseCommand: "scripts/post-release.sh"
artifactProvider:
  name: none
targets:
- name: github
versioning:
  policy: calver
